---
services:
  ntp:
    build: .
    image: henryhst/ha-chronyd:main
    container_name: ntp
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750,uid=100,gid=101
      - /run/chrony:rw,mode=1750,uid=100,gid=101
      - /var/lib/chrony:rw,mode=1750,uid=100,gid=101
    ports:
      - 123:123/udp
# if you'd like chronyd to synchronize your hosts clock, uncomment these settings
#    user: "0:0"
#    cap_add:
#      - SYS_TIME
#     devices:
#       - /dev/ptp0:/dev/ptp0
    environment:
      - NTP_SERVERS=de.pool.ntp.org
      - LOG_LEVEL=0
#      - TZ=Europe/Berlin
#      - NOCLIENTLOG=true
#      - ENABLE_NTS=true
#      - ENABLE_SYSCLK=true
